### ISSUE TITLE
在爬取这个视频时遇到了错误

### ISSUE THREAD

**Issue by shiyishiaa** [CyrusRenty/MOOC-Download#1]
HUST-481015
选的超清，错误闪太快没看清
但是选高清的话没问题

**Comment by shiyishiaa** [comment]
另外，Rename.bat这个批处理应该用ANSI格式保存，否则重命名会乱码

**Comment by itstyren** [comment]
> 
> 
> HUST-481015
> 选的超清，错误闪太快没看清
> 但是选高清的话没问题

你好，出现这个问题是因为你这个课第二章课程小结没有超清的选项，过两天我更改一下判断逻辑。重命名批处理我这边几台电脑测试没有出现乱码问题，如果还有人有问题我再改一下。

**Comment by itstyren** [comment]
已更改，谢谢你的issue，如还有问题请与我联系。
